import Head from 'next/head'
import { Roboto } from 'next/font/google'
import { getCssText, Heading, Text } from '@ignite-ui/react'
import { Container, Hero, Preview } from './styles'

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] })

import previewImage from '../../assets/app-preview.png'
import Image from 'next/image'
import { ClaimUserNameForm } from './components/ClaimUserNameForm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </Head>
      <main className={roboto.className}>
        <Container>
          <Hero>
            <Heading as="h1" size="4xl" >Agendamento descomplicado</Heading>

            <Text size="lg">Conecte seu calendário e permita que as pessoas marquem agendamentos no seu tempo livre.</Text>

            <ClaimUserNameForm />
          </Hero>

          <Preview>
            <Image 
              src={previewImage} 
              alt='Calendário simbolizando aplicação em funcionamento.' 
              height={400}
              quality={100}
              priority  
            />
          </Preview>
        </Container>
      </main>
    </>
  )
}
